#!/usr/bin/env python3
"""Emit a deterministic SMPL-X pose sweep JSON for ROM sampling."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def build_sweep(
    *,
    shoulder: float,
    hip: float,
    knee: float,
    twist: float,
    elbow: float,
) -> dict:
    """Construct a simple, deterministic pose sweep."""

    return {
        "meta": {
            "units": "radians",
            "joint_layout": "smplx_body_v1",
            "notes": "Deterministic pose sweep generated by generate_pose_sweep.py",
        },
        "neutral": {"global_orient": [0.0, 0.0, 0.0]},
        "poses": [
            {"id": "neutral"},
            {
                "id": "arms_up",
                "weight": 1.0,
                "body_pose": {
                    "left_shoulder": [shoulder, 0.0, 0.0],
                    "right_shoulder": [-shoulder, 0.0, 0.0],
                },
                "notes": "Symmetric shoulder flexion",
            },
            {
                "id": "hips_knees",
                "weight": 1.0,
                "body_pose": {
                    "left_hip": [hip, 0.0, 0.0],
                    "right_hip": [-hip, 0.0, 0.0],
                    "left_knee": [knee, 0.0, 0.0],
                    "right_knee": [knee, 0.0, 0.0],
                },
                "notes": "Moderate hip and knee flexion",
            },
            {
                "id": "twist_reach",
                "weight": 1.0,
                "global_orient": [0.0, twist * 0.6, 0.0],
                "body_pose": {
                    "spine1": [0.0, 0.0, twist * 0.8],
                    "spine2": [0.0, 0.0, twist],
                    "spine3": [0.0, 0.0, twist],
                    "left_shoulder": [shoulder * 0.55, 0.0, twist],
                    "right_shoulder": [-shoulder * 0.55, 0.0, -twist],
                    "left_elbow": [elbow, 0.0, 0.0],
                    "right_elbow": [elbow, 0.0, 0.0],
                },
                "notes": "Axial twist with reaching elbows",
            },
        ],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("data/rom/afflec_sweep.json"),
        help="Path to write the pose sweep JSON (default: data/rom/afflec_sweep.json).",
    )
    parser.add_argument("--shoulder", type=float, default=0.85, help="Shoulder flexion (radians).")
    parser.add_argument("--hip", type=float, default=0.35, help="Hip flexion (radians).")
    parser.add_argument("--knee", type=float, default=0.70, help="Knee flexion (radians).")
    parser.add_argument("--twist", type=float, default=0.25, help="Axial twist magnitude (radians).")
    parser.add_argument("--elbow", type=float, default=0.35, help="Elbow flexion (radians).")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = build_sweep(
        shoulder=args.shoulder,
        hip=args.hip,
        knee=args.knee,
        twist=args.twist,
        elbow=args.elbow,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote pose sweep to {args.out}")


if __name__ == "__main__":
    main()
